"""Add signature_data column to users table

Revision ID: 5e7209ce41a2
Revises: 
Create Date: 2026-02-12 00:00:28.707852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7209ce41a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    op.drop_table('prescription_items')
    with op.batch_alter_table('doctor_leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_leaves_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_leaves_leave_date'))

    op.drop_table('doctor_leaves')
    with op.batch_alter_table('inventory_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_locks_expires_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_locks_inventory_id'))

    op.drop_table('inventory_locks')
    with op.batch_alter_table('appointment_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_waitlist_created_at'))
        batch_op.drop_index(batch_op.f('ix_appointment_waitlist_preferred_date'))
        batch_op.drop_index(batch_op.f('ix_appointment_waitlist_student_id'))

    op.drop_table('appointment_waitlist')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_visit_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_schedules_doctor_id'))

    op.drop_table('doctor_schedules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('signature_data')

    op.create_table('doctor_schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('max_patients', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name=op.f('valid_day_of_week')),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', 'start_time', 'service_type', name=op.f('unique_doctor_schedule'))
    )
    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_schedules_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('visit_id', sa.INTEGER(), nullable=False),
    sa.Column('prescribed_by', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('prescribed_at', sa.DATETIME(), nullable=True),
    sa.Column('digital_signature', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['clinic_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_visit_id'), ['visit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)

    op.create_table('appointment_waitlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('preferred_date', sa.DATE(), nullable=False),
    sa.Column('preferred_time', sa.TIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('notified_at', sa.DATETIME(), nullable=True),
    sa.Column('converted_to_appointment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['converted_to_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_waitlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_waitlist_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_waitlist_preferred_date'), ['preferred_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_waitlist_created_at'), ['created_at'], unique=False)

    op.create_table('inventory_locks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_locked', sa.INTEGER(), nullable=False),
    sa.Column('locked_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['medicine_reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_locks_inventory_id'), ['inventory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_locks_expires_at'), ['expires_at'], unique=False)

    op.create_table('doctor_leaves',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('leave_date', sa.DATE(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'leave_date', name=op.f('unique_doctor_leave'))
    )
    with op.batch_alter_table('doctor_leaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_leaves_leave_date'), ['leave_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_leaves_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('prescription_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prescription_id', sa.INTEGER(), nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_prescribed', sa.INTEGER(), nullable=False),
    sa.Column('quantity_dispensed', sa.INTEGER(), nullable=False),
    sa.Column('dosage_instructions', sa.TEXT(), nullable=True),
    sa.Column('dispensed_at', sa.DATETIME(), nullable=True),
    sa.Column('dispensed_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_id', sa.INTEGER(), nullable=True),
    sa.Column('old_value', sa.TEXT(), nullable=True),
    sa.Column('new_value', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    # ### end Alembic commands ###
